create table bills (id bigint not null auto_increment, amount integer, description varchar(255), player_name varchar(50), time datetime, primary key (id)) engine=InnoDB;
create table card_group (id bigint not null auto_increment, name varchar(50), player_name varchar(50), primary key (id)) engine=InnoDB;
create table card_packet (id bigint not null auto_increment, price integer, name varchar(50), primary key (id)) engine=InnoDB;
create table cards (id bigint not null auto_increment, description varchar(255), name varchar(50), rarity integer, type varchar(50), primary key (id)) engine=InnoDB;
create table forbids (id bigint not null auto_increment,play_name varchar(50),manager_name varchar(50), end datetime, start datetime, primary key (id)) engine=InnoDB;
create table game_record (id bigint not null auto_increment, time datetime, loser varchar(50) not null, winner varchar(50) not null, primary key (id)) engine=InnoDB;
create table group_item (id bigint not null auto_increment, card_id bigint not null, card_group_id bigint not null, primary key (id)) engine=InnoDB;
create table players (name varchar(50) not null, email varchar(30), identity smallint, password varchar(100), phone_number varchar(15), account bigint, defeats integer, joined bit, nickname varchar(50), ranking integer, primary key (name)) engine=InnoDB;
create table users (name varchar(50) not null, email varchar(30), identity smallint, password varchar(100), phone_number varchar(15), primary key (name)) engine=InnoDB;
create table has_card (player_name varchar(50) not null,number integer not null, card_id bigint not null, primary key (player_name, card_id)) engine=InnoDB;
alter table bills add constraint FK685xndnjpuktk08yafplbybhh foreign key (player_name) references players (name);
alter table card_group add constraint FKg53uwr5ir5kxu0cdo1d3yw88k foreign key (player_name) references players (name);
alter table game_record add constraint FKbbja9bo4bh2ovpueb601o2wpb foreign key (loser) references players (name);
alter table game_record add constraint FKswr9evrdlbxlvc4wv3ipu780s foreign key (winner) references players (name);
alter table group_item add constraint FKjer5e5787bb1cplttdvndinbq foreign key (card_id) references cards (id);
alter table group_item add constraint FKkkmq7yj9vam5fyux6ego931kp foreign key (card_group_id) references card_group (id);
alter table has_card add constraint FKlk20t54xjm253m88vlq3gcra2 foreign key (card_id) references cards (id);
alter table has_card add constraint FK14bsi56apjg032pk80uk8gtmj foreign key (player_name) references players (name);
